# Generated by Django 4.1.3 on 2022-11-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AlterField(
            model_name='company',
            name='advocates',
            field=models.ManyToManyField(blank=True, to='base.advocate'),
        ),
    ]
